on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

name: SonarQube Scan
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    env:  # Set environment variables
      SONAR_SCANNER_OPTS: -Dsonar.log.level=DEBUG  # This is an example, check the correct option for log level
    steps:
      - name: Checking out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          sonar-token: ${{ secrets.MY_GITHUB_TOKEN }}
